/**
 *
 * $Id$
 */
package orchestration.validation;

import orchestration.Agent;
import orchestration.Git;
import orchestration.LLM;
import orchestration.Maven;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link orchestration.Orchestrator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrchestratorValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateAgents(EList<Agent> value);
	boolean validateGit(Git value);
	boolean validateMaven(Maven value);
	boolean validateLlm(LLM value);
	boolean validateCompiler(orchestration.Compiler value);
}
