source.. = src/
output.. = bin/
bin.includes = META-INF/,               .,               plugin.xml,               template.html,               evolution.css,               evolution.js
jars.extra.classpath = platform:/plugin/org.eclipse.debug.core/,                       platform:/plugin/org.eclipse.core.resources/,                       platform:/plugin/org.eclipse.jdt.launching/,                       platform:/plugin/org.eclipse.equinox.common/
access.rules = **
