/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import org.eclipse.emf.common.util.EList;

import eu.kalafatic.evolution.model.orchestration.AiMode;
import eu.kalafatic.evolution.model.orchestration.ChatMessage;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.ChatSession}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChatSessionValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateMessages(EList<ChatMessage> value);
	boolean validateIterativeMode(boolean value);
	boolean validateSelfIterativeMode(boolean value);
	boolean validateDarwinMode(boolean value);
	boolean validateGitAutomation(boolean value);
	boolean validateMaxIterations(int value);
	boolean validateStepMode(boolean value);
	boolean validateTargetPath(String value);
	boolean validateTargetType(String value);
	boolean validateOutputPath(String value);
	boolean validateAutoApprove(boolean value);
	boolean validateAiMode(AiMode value);
	boolean validateLocalModel(String value);
	boolean validateRemoteModel(String value);
	boolean validateBitState(long value);
	boolean validateExpansion(int value);
}
