/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.CommandStatus;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Command}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommandValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateStatus(CommandStatus value);
}
