/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.ForgeStatus;
import eu.kalafatic.evolution.model.orchestration.SessionExperiment;
import eu.kalafatic.evolution.model.orchestration.SessionModelState;
import eu.kalafatic.evolution.model.orchestration.SessionSnapshot;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.ForgeSession}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForgeSessionValidator {
	boolean validate();

	boolean validateSessionId(String value);
	boolean validateName(String value);
	boolean validateCreatedAt(long value);
	boolean validateLastModified(long value);
	boolean validateStatus(ForgeStatus value);
	boolean validateActiveModelId(String value);
	boolean validateSelectedModelType(String value);
	boolean validateModelState(SessionModelState value);
	boolean validateExperiments(EList<SessionExperiment> value);
	boolean validateSnapshots(EList<SessionSnapshot> value);
}
