/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.NeuronType;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.NeuronAI}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NeuronAIValidator {
	boolean validate();

	boolean validateUrl(String value);
	boolean validateModel(String value);
	boolean validateType(NeuronType value);
}
