/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.Agent;
import eu.kalafatic.evolution.model.orchestration.Git;
import eu.kalafatic.evolution.model.orchestration.LLM;
import eu.kalafatic.evolution.model.orchestration.Maven;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Orchestrator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrchestratorValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateAgents(EList<Agent> value);
	boolean validateGit(Git value);
	boolean validateMaven(Maven value);
	boolean validateLlm(LLM value);
	boolean validateCompiler(eu.kalafatic.evolution.model.orchestration.Compiler value);
}
