/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.SessionSnapshot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SessionSnapshotValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateSessionId(String value);
	boolean validateGenomeSnapshotId(String value);
	boolean validateFullSerializedState(String value);
	boolean validateTimestamp(long value);
}
