/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.SessionModelState}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SessionModelStateValidator {
	boolean validate();

	boolean validateSessionId(String value);
	boolean validateModelGraph(String value);
	boolean validateHyperparameters(String value);
	boolean validateDatasetBindings(String value);
	boolean validateRuntimeState(String value);
}
