source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               prompts/,\
               css/,\
               js/,\
               chat.html,\
               chat2.html,\
               chat3.html,\
               splash.bmp,\
               plugin_customization.ini,\
               evo.product,\
               evolution.product,\
               workflow/
