source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               splash.bmp,\
               plugin_customization.ini,\
               lib/json-20140107.jar,\
               products/
jars.extra.classpath = lib/json-20140107.jar
